In [1]:
import os
import matplotlib.pyplot as plt

### 텐서플로우와 판다스 라이브러리를 import하십시오

In [2]:
# your code here
import pandas as pd
import tensorflow as tf

### 왓슨 스튜디오 주피터 노트북의 Insert to Code 기능을 이용하여 offences.csv 파일을 판다스 dataframe 포탯으로 읽고 df.head()로 내용을 출력하십시오.

In [16]:
# your code here
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_f52f41bbb2224b2fa87c1a9e11596026 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='E6EbzKXKBaAOJfhqvotuIr0yL08X91_uPFBP0-zf0wbf',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_f52f41bbb2224b2fa87c1a9e11596026.get_object(Bucket='midexam2-donotdelete-pr-dqqvg2guz6a5ke',Key='Offences.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head()

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3,Unnamed: 13
0,Abernathy,2821.0,0.0,0.0,NaN,0.0,0.0,0.0,12.0,12.0,0.0,0.0,1.0,NaN
1,Abilene,119401.0,477.0,1.0,NaN,37.0,125.0,314.0,4769.0,1055.0,3460.0,254.0,16.0,NaN
2,Addison,15961.0,51.0,1.0,NaN,4.0,11.0,35.0,784.0,129.0,593.0,62.0,1.0,NaN
3,Alamo,18876.0,164.0,0.0,NaN,11.0,27.0,126.0,1336.0,203.0,1052.0,81.0,1.0,NaN
4,Alamo Heights,7443.0,9.0,0.0,NaN,2.0,2.0,5.0,235.0,36.0,194.0,5.0,0.0,NaN

In [17]:
df = df.loc[:, ['Burglary', 'Murder and\nnonnegligent\nmanslaughter']]
df.columns = ['Burlaries', 'Manslaughter']

###  pandas의 dropna()를 사용하여 NaN이 있는 row들을 삭제하고 그 결과를 원래의 df 오브젝트로 저장하십시오. 
### 참조: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html

In [19]:
# your code here
df = df.dropna()
df.head()

   Burlaries  Manslaughter
0       12.0           0.0
1     1055.0           1.0
2      129.0           1.0
3      203.0           0.0
4       36.0           0.0

In [20]:
learningRate = 0.0000001
numEpochs = 100

### x와 y 변수 두 개를 tf.placeholder를 사용하여 선언하십시오. dtype은 float32, shape는 [None, ]

In [29]:
# your code here 
x = tf.placeholder(dtype = tf.float32, shape = None)
y = tf.placeholder(dtype = tf.float32, shape = None)

### w와 b 두 텐서를 모두 0으로 초기화 shape는 [1]

In [30]:
w = tf.Variable(tf.zeros(shape=[1]))
b = tf.Variable(tf.zeros(shape=[1]))

### 아래 셀 중에 your code here 부분을 완성하십시오.

In [31]:
# Predictor변수를 y_pred로 이름짓고 y_pred = x * W + b 텐서 연산을 정의하십시오
y_pred = (x*w) + b

# loss 함수를 최소자승법을 사용하여 정의하십시오. y와 y_pred의 차이의 제곱을 사용
loss = tf.reduce_mean(tf.square(y_pred - y))

# optimizer를 기본 경사하강법을 사용하여 정의하십시오.
optimiser = tf.train.GradientDescentOptimizer(learning_rate=1e-2).minimize(loss)

with tf.Session() as session:
    session.run(tf.global_variables_initializer())

    input, output = df.iloc[:, 0], df.iloc[:, 1]
    for epoch in range(numEpochs):
        _, sampleLoss, pred = session.run([optimiser, loss, y_pred], {x: input, y: output})
        print("EPOCH:", epoch + 1)
        print("LOSS: ", sampleLoss)
        print("")

    y_preds = session.run(y_pred, {x: input, y: output})

EPOCH: 1
LOSS:  126.39901

EPOCH: 2
LOSS:  176626100000.0

EPOCH: 3
LOSS:  2.6710557e+20

EPOCH: 4
LOSS:  4.0393434e+29

EPOCH: 5
LOSS:  inf

EPOCH: 6
LOSS:  inf

EPOCH: 7
LOSS:  inf

EPOCH: 8
LOSS:  inf

EPOCH: 9
LOSS:  inf

EPOCH: 10
LOSS:  nan

EPOCH: 11
LOSS:  nan

EPOCH: 12
LOSS:  nan

EPOCH: 13
LOSS:  nan

EPOCH: 14
LOSS:  nan

EPOCH: 15
LOSS:  nan

EPOCH: 16
LOSS:  nan

EPOCH: 17
LOSS:  nan

EPOCH: 18
LOSS:  nan

EPOCH: 19
LOSS:  nan

EPOCH: 20
LOSS:  nan

EPOCH: 21
LOSS:  nan

EPOCH: 22
LOSS:  nan

EPOCH: 23
LOSS:  nan

EPOCH: 24
LOSS:  nan

EPOCH: 25
LOSS:  nan

EPOCH: 26
LOSS:  nan

EPOCH: 27
LOSS:  nan

EPOCH: 28
LOSS:  nan

EPOCH: 29
LOSS:  nan

EPOCH: 30
LOSS:  nan

EPOCH: 31
LOSS:  nan

EPOCH: 32
LOSS:  nan

EPOCH: 33
LOSS:  nan

EPOCH: 34
LOSS:  nan

EPOCH: 35
LOSS:  nan

EPOCH: 36
LOSS:  nan

EPOCH: 37
LOSS:  nan

EPOCH: 38
LOSS:  nan

EPOCH: 39
LOSS:  nan

EPOCH: 40
LOSS:  nan

EPOCH: 41
LOSS:  nan

EPOCH: 42
LOSS:  nan

EPOCH: 43
LOSS:  nan

EPOCH: 44
LOSS:  nan

EPOCH: 45
LOSS:  nan

EPOCH: 46
LOSS:  nan

EPOCH: 47
LOSS:  nan

EPOCH: 48
LOSS:  nan

EPOCH: 49
LOSS:  nan

EPOCH: 50
LOSS:  nan

EPOCH: 51
LOSS:  nan

EPOCH: 52
LOSS:  nan

EPOCH: 53
LOSS:  nan

EPOCH: 54
LOSS:  nan

EPOCH: 55
LOSS:  nan

EPOCH: 56
LOSS:  nan

EPOCH: 57
LOSS:  nan

EPOCH: 58
LOSS:  nan

EPOCH: 59
LOSS:  nan

EPOCH: 60
LOSS:  nan

EPOCH: 61
LOSS:  nan

EPOCH: 62
LOSS:  nan

EPOCH: 63
LOSS:  nan

EPOCH: 64
LOSS:  nan

EPOCH: 65
LOSS:  nan

EPOCH: 66
LOSS:  nan

EPOCH: 67
LOSS:  nan

EPOCH: 68
LOSS:  nan

EPOCH: 69
LOSS:  nan

EPOCH: 70
LOSS:  nan

EPOCH: 71
LOSS:  nan

EPOCH: 72
LOSS:  nan

EPOCH: 73
LOSS:  nan

EPOCH: 74
LOSS:  nan

EPOCH: 75
LOSS:  nan

EPOCH: 76
LOSS:  nan

EPOCH: 77
LOSS:  nan

EPOCH: 78
LOSS:  nan

EPOCH: 79
LOSS:  nan

EPOCH: 80
LOSS:  nan

EPOCH: 81
LOSS:  nan

EPOCH: 82
LOSS:  nan

EPOCH: 83
LOSS:  nan

EPOCH: 84
LOSS:  nan

EPOCH: 85
LOSS:  nan

EPOCH: 86
LOSS:  nan

EPOCH: 87
LOSS:  nan

EPOCH: 88
LOSS:  nan

EPOCH: 89
LOSS:  nan

EPOCH: 90
LOSS:  nan

EPOCH: 91
LOSS:  nan

EPOCH: 92
LOSS:  nan

EPOCH: 93
LOSS:  nan

EPOCH: 94
LOSS:  nan

EPOCH: 95
LOSS:  nan

EPOCH: 96
LOSS:  nan

EPOCH: 97
LOSS:  nan

EPOCH: 98
LOSS:  nan

EPOCH: 99
LOSS:  nan

EPOCH: 100
LOSS:  nan

In [ ]:
for i in range(df.shape[0]):
    x, y = df.iloc[i, 0], df.iloc[i, 1]
    plt.scatter(x, y, c='b')

plt.plot(input, y_preds, c='r')

plt.show()